### ISSUE TITLE
Parsing error loading recipe xp_storage:crystallized_lapis_dust

### ISSUE THREAD

**Issue by MJRamon** [sf-inc/xp_storage#30]
```
[main/ERROR]: Parsing error loading recipe xp_storage:crystallized_lapis_dust
com.google.gson.JsonSyntaxException: Unknown item 'xp_storage:crystallized_lapis_dust'
	at net.minecraft.class_1869.method_17878(class_1869.java:272) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_1869.method_35228(class_1869.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:99) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
```

**Comment by charlyb01** [comment]
Duplicate from #29
